default_language_version:
    python: python3.12

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff
        files: "^django_pydantic_field/"
        exclude: ^.*\b(\.pytest_cache|\.venv|venv).*\b.*$
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        files: "^django_pydantic_field/"
        exclude: ^.*\b(\.pytest_cache|\.venv|venv).*\b.*$